#!/usr/bin/env ruby

require 'json'
require 'open3'
require 'fileutils'

file = File.read('ionic.config.json')
data_hash = JSON.parse(file)
app_name = data_hash['name']
clean_name = app_name.delete('-').downcase
cmd = "ionic package build android --profile #{clean_name}_production --release"
build_id = nil
Open3.popen2e(cmd) do |_stdin, stdout_err, wait_thr|
  while line = stdout_err.gets
    puts line
    result = line.match(/Build ID: (\d+)/)
    build_id = result[1] unless result.nil?
  end
  raise unless wait_thr.value.exitstatus === 0
end

build_info = `ionic package info #{build_id}`
while (build_info =~ /SUCCESS/).nil?
  puts 'waiting for download...'
  sleep(1)
end
puts `ionic package download #{build_id}`
FileUtils.mv("#{app_name}.apk", "#{ENV['CIRCLE_ARTIFACTS']}/#{app_name}.apk")
